In [1]:
import pandas as pd 
import numpy as np

## Opdracht 1 hotel

In [5]:
df = pd.read_excel('hotelBookings.xlsx')
print(df.shape)
df.head()

(1000, 32)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0.0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0.0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1.0,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1.0,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2.0,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [13]:
# The columns 'Market' and 'Distribution Channel' are not relevant
# Some values of adults and children are outliers. These seem to be data entry errors. So many people cannot fit one room
# Year has missing values
# Is_Cancelled contains a 2, but this column is binary
# Stays_in_week_nights contains a number with a ,
# Meal has a lot of trailing spaces
# Country has trailing spaces and contains numbers
# Agent and Company contains NULL and null
# Adr numbers are not real numbers
# Duplicates

In [9]:
df = pd.read_excel("hotelBookings.xlsx")

df = df.drop_duplicates()
df["company"] = df["company"].fillna(0)
df["agent"] = df["agent"].fillna(0)
df["stays_in_week_nights"] = df["stays_in_week_nights"].astype(int)
df["arrival_date_month"] = pd.to_datetime(df['arrival_date_month'], format='%B').dt.strftime('%m')

In [10]:
df['adults'].sort_values(ascending=False) # kijken of er outliers zijn in de data 
print(df[df['adults'] > 4]) # net gezien dat er een kamer is met 3500 adults wat dus niet kan 4 is realistisch aantal
df = df[df['adults'] <= 4] # verwijder alle rijen waarbij er meer dan 4 adults zijn
df['children'].sort_values(ascending=False) # het zelfde voor children 
df = df[df['children']<=4]

            hotel  is_canceled  lead_time  arrival_date_year  \
195  Resort Hotel            0         65               2015

    arrival_date_month  arrival_date_week_number  arrival_date_day_of_month  \
195                 07                        28                          6

     stays_in_weekend_nights  stays_in_week_nights  adults  ...  deposit_type  \
195                        2                     5    3500  ...    No Deposit

     agent company days_in_waiting_list customer_type   adr  \
195  127.0     0.0                    0     Transient  83.5

     required_car_parking_spaces  total_of_special_requests  \
195                            0                          0

     reservation_status reservation_status_date
195           Check-Out              2015-07-13

[1 rows x 32 columns]

In [11]:
df['country'] = df['country'].str.strip() # de spaties verwijderen 
df['country'] = df['country'].str.replace(r'\d+', '', regex=True) # verwijder de cijfers

In [12]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,07,27,1,0,0,2,...,No Deposit,0.0,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,07,27,1,0,0,2,...,No Deposit,0.0,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,07,27,1,0,1,1,...,No Deposit,0.0,0.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,07,27,1,0,1,1,...,No Deposit,304.0,0.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,07,27,1,0,2,2,...,No Deposit,240.0,0.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Resort Hotel,0,34,2015,08,33,9,2,2,2,...,No Deposit,240.0,0.0,0,Transient,211.00,0,1,Check-Out,2015-08-13
996,Resort Hotel,0,82,2015,08,33,9,2,2,2,...,No Deposit,240.0,0.0,0,Transient,154.00,0,0,Check-Out,2015-08-13
997,Resort Hotel,1,65,2015,08,33,9,2,3,2,...,No Deposit,240.0,0.0,0,Transient,145.40,0,0,Canceled,2015-06-22
998,Resort Hotel,1,129,2015,08,33,9,2,3,1,...,No Deposit,240.0,0.0,0,Transient,101.25,0,0,Canceled,2015-04-06
999,Resort Hotel,0,55,2015,08,33,9,2,4,2,...,No Deposit,242.0,0.0,0,Transient,179.38,0,0,Check-Out,2015-08-15

## Opdracht 3

In [14]:
import pandas as pd

def generate_sales_report(file_path):
    """
    Generates a sales report based on data from an Excel file.

    Args:
        file_path (str): The path to the Excel file.

    Returns:
        pd.DataFrame: The sales report containing total sales and contribution for categories, months, and managers.
    """
    # Read the Excel file
    data = pd.read_excel(file_path)

    # Calculate total sales and contribution by category
    category_sales = data.groupby('Category')['Sales'].sum().dropna()
    total_sales_category = category_sales.sum()
    category_contributions = category_sales / total_sales_category * 100

    # Calculate total sales and contribution by month
    month_sales = data.groupby('Month')['Sales'].sum()
    total_sales_month = month_sales.sum()
    month_contributions = month_sales / total_sales_month * 100

    # Calculate total sales and contribution by manager
    manager_sales = data.groupby('Sales Manager')['Sales'].sum()
    total_sales_manager = manager_sales.sum()
    manager_contributions = manager_sales / total_sales_manager * 100

    # Generate the sales report
    report = pd.DataFrame({
        'Total Sales by Category': category_sales,
        'Contribution Category (%)': category_contributions,
        'Total Sales by Month': month_sales,
        'Contribution Month (%)': month_contributions,
        'Total Sales by Manager': manager_sales,
        'Contribution Manager (%)': manager_contributions
    })

    # Sort the report by category, month, and manager
    report = report.sort_values(by=['Total Sales by Category', 'Total Sales by Month', 'Total Sales by Manager'],
                                ascending=False)

    return report
# Usage
# Specify the file path of the Excel file
file_path = 'detailedRetail.xlsx'

# Generate the sales report
sales_report = generate_sales_report(file_path)

# Save the sales report to an Excel file
output_file_path = 'reportRetail.xlsx'
sales_report.to_excel(output_file_path, index=True)

# Confirm the file is saved
print(f"The sales report has been saved to '{output_file_path}'.")

BadZipFile: File is not a zip file

In [ ]:
import pandas as pd
from langdetect import detect , LangDetectException
from textblob import TextBlob
from nltk.sentiment import SentimentIntensityAnalyzer
import nltk
 
 
df = pd.read_excel('tweets.xlsx')
df
 
# functie om tekijken welke taal de tweet
def detect_language(text):
    try:
        # zorgen dat de txt een string is
        if isinstance(text, str):
            return detect(text)
        else:
            return "Unknown"
    except LangDetectException:
        return "Unknown"
 
# functie toepassen en nieuwe colom Language toevoegen
df['Language'] = df['Tweet'].apply(detect_language)
 
# Output
for idx, row in df.iterrows():
    print(f"{idx} {row['Tweet']} {row['Language']}")
 
 
nltk.download('vader_lexicon')
 
# SentimentIntensityAnalyzer object
sia = SentimentIntensityAnalyzer()
 
# sentiment van engelse tweet met textblob
def analyze_sentiment_english(tweet):
    blob = TextBlob(tweet)
    polarity = blob.sentiment.polarity
    if polarity > 0:
        return 'positive'
    elif polarity < 0:
        return 'negative'
    else:
        return 'neutral'
 
# functie die sentiment van niet engelse tweet checkt met sia
def analyze_sentiment_other(tweet):
    scores = sia.polarity_scores(tweet)
    compound = scores['compound']
    if compound >= 0.05:
        return 'positive'
    elif compound <= -0.05:
        return 'negative'
    else:
        return 'neutral'
 
 
# functies voor sentiment voor engelse en niet engelse toepassen
def apply_sentiment_analysis(row):
    tweet = row['Tweet']
    language = row['Language']
   
    if language == 'en':
        return analyze_sentiment_english(tweet)
    else:
        return analyze_sentiment_other(tweet)
 
# nieuwe colom aanmaken
df['sentiment'] = df.apply(apply_sentiment_analysis, axis=1)
 
 
print(df)